graph TD
    n-design-studies-ba2bad["design-studies\ndesign-studies"]
    n-docker-e982f1["docker\ndocker"]
    n-docs-71ab8b["docs\ndocs"]
    n-examples-99345c["examples\nexamples"]
    n-homepage-568be0["homepage\nhomepage"]
    n-launchloom-8638dc["launchloom\nlaunchloom"]
    n-pyproject-toml-5d07e7["pyproject.toml\npyproject.toml"]
    n-scripts-16728d["scripts\nscripts"]
